# Generated by Django 4.0.4 on 2022-06-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='h1',
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
